config/routes.rb
Rails.application.routes.draw do
  
  get 'books/index'
  get 'books/show'
  get 'books/new'
  get 'books/edit'
  get 'books/delete'
  root 'demo#index'
  
  resources :books
  
  
  get 'demo/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
  get 'demo/practice'
  #default route
  #get ':controller(/:action(/:id))' 

  get 'demo2/index2'  
  
  get 'demo/hello'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :info
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
	@books = Book.order('id ASC')
  end

  def show
	@book = Book.find(params[:id])
  end

  def new
	@book = Book.new
	
  end
  
  def create
	@book = Book.new(subject_params)
	if @book.save
		redirect_to(books_index_path)
		flash[:notice] =  "The book #{@book.title} was added successfully"
	else
		render('new')
	end
  end

  def edit
	@book = Book.find(params[:id])
  end
  
  def update
	@book = Book.find(params[:id])
	if @book.update(subject_params)
		redirect_to(books_index_path)
		flash[:notice] =  "The book #{@book.title} was updated successfully"
	else
		render('edit')
	end
  end

  def delete
	@book = Book.find(params[:id])
  end
  
  def destroy
	@book = Book.find(params[:id])
	@book.destroy
	redirect_to(books_index_path)
	flash[:notice] =  "The book #{@book.title} was deleted successfully"
  end
  
  private
	
	def subject_params
			params.require(:book).permit(:title, :author, :genre, :price, :publishDate)
	end
end

app/controllers/demo2_controller.rb
class Demo2Controller < ApplicationController
  def index2
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false
  
  def index
	#render ('index')
	@array = [1,2,3,4,5]
	@id = params['id']
	@page = params[:page]
  end
  
  def hello
	#render ('hello')
	#redirect_to(:controller => 'demo', :action => 'index')
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demo2_helper.rb
module Demo2Helper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/books/delete.html.erb
<br/>
<br/>

<%= link_to("<< Back to List", books_index_path, :class => 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, :method => 'delete') do |f| %>

    <p> Are you sure you want to delete this entry? </p>
	<p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<br/>
<br/>

<%= link_to("<< Back to List", books_index_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Edit Book</h2>

  <%= form_for(@book) do |f| %>

    <table summary="Book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.select :genre, [['fiction', 'fiction'], ['nonfiction', 'nonfiction'], ['SciFi', 'SciFi'], ['Action/Adventure', 'action/adventure'], ['romance', 'romance'], ['history', 'history']] %></td>
      </tr>
	  <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
	  <tr>
        <th>Publish Date</th>
        <td><%= f.select :publishDate, [['2000', '2000'], ['2001', '2001'], ['2002', '2002'], ['2003', '2003'],
				['2004', '2004'], ['2005', '2005'], ['2006', '2006'], ['2007', '2007'], ['2008', '2008'],
				['2009', '2009'], ['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'],
				['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'],
				['2019', '2019'], ['2020', '2020'], ['2021', '2021']]%></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<br/>
<br/>
<%flash.each do |type, msg| %>
	<div>
		<%= msg %>
	</div>
<% end %>
<div class="books index">
  <h2>Books</h2>

  <%= link_to("Add new Book", books_new_path, :class => 'action new') %>

  <table class="listing" summary="Book list">
    <tr class="header">
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Price</th>
	  <th>Publish Date</th>
      <th>Actions</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
	  <td><%= book.genre %></td>
	  <td><%= book.price %></td>
	  <td><%= book.publishDate %></td>

      <td class="actions">
        <%= link_to("Show", {:action => 'show', :id => book.id}, :class => 'action show') %>
        <%= link_to("Edit", {:action => 'edit', :id => book.id}, :class => 'action edit') %>
        <%= link_to("Delete", {:action => 'delete', :id => book.id}, :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<br/>
<br/>

<%= link_to("<< Back to List", books_index_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create Book</h2>

  <%= form_for(@book) do |f| %>

    <table summary="Book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.select :genre, [['fiction', 'fiction'], ['nonfiction', 'nonfiction'], ['SciFi', 'SciFi'], ['Action/Adventure', 'action/adventure'], ['romance', 'romance'], ['history', 'history']] %></td>
      </tr>
	  <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
	  <tr>
        <th>Publish Date</th>
        <td><%= f.select :publishDate, [['2000', '2000'], ['2001', '2001'], ['2002', '2002'], ['2003', '2003'],
				['2004', '2004'], ['2005', '2005'], ['2006', '2006'], ['2007', '2007'], ['2008', '2008'],
				['2009', '2009'], ['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'],
				['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'],
				['2019', '2019'], ['2020', '2020'], ['2021', '2021']]%></td>
				
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<br/>
<br/>

<%= link_to("<< Back to List", books_index_path, :class => 'back-link') %>

<div class="books show">
  <h2>Show Book</h2>

  <table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @book.genre %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Publish Date</th>
      <td><%= @book.publishDate %></td>
    </tr>
  </table>

</div>

app/views/demo/hello.html.erb
<h1> meep hello meep </h1>
<br/>
<%= link_to("Index page", {:action => 'index'}) %><br/>
ID: <%= @id %> <br/> 
ID: <%= params[:id] %><br/>
Page: <%= @page %> <br/>

app/views/demo/index.html.erb
<h1>Hello World</h1>
<%= 1 + 1 %>
<br/>
<% target = 'world' %>
<%= "Hello #{target}!" %>

<% @array.each do |n| %>
	<p><%= n %></p>
<% end %>

<a href = "/demo/hello"> Hello Page 1 </a><br/>
<%= link_to("Hello page 2", {:action => 'hello'}) %>

<br/> 

<%= link_to("Hello with parameters", {:action => 'hello', :page => 5, :id => 20}) %>

<br/>

<%= link_to('all books', books_index_path) %>

app/views/demo/practice.html.erb
<h1> this is practice </h1>

app/views/demo2/index2.html.erb
<h1>Demo2#index2</h1>
<p>Find me in app/views/demo2/index2.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>